name: Budget

on: workflow_dispatch

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Api-tests
        run: |
          docker compose up --exit-code-from moneybox_tests || true
          

      - name: Generate Allure report
        run: |
          sudo docker compose run moneybox_tests /bin/sh -c "allure generate allure-results --clean -o allure-report"


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true